version: "3.8"
services:
  rawg-to-steam-redirect:
    build: .
    ports:
      - "80:9999"
    restart: always
    develop:
      watch:
        - action: rebuild
          path: .
          target: /usr/src/app

